-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 29, 2017 at 11:00 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kios`
--

-- --------------------------------------------------------

--
-- Table structure for table `2011infokios`
--

CREATE TABLE `2011infokios` (
  `id` int(10) UNSIGNED NOT NULL,
  `kios` text NOT NULL,
  `admin` text NOT NULL,
  `tglkirim` text NOT NULL,
  `judulberita` text NOT NULL,
  `deskripsi` text NOT NULL,
  `photoberita` text NOT NULL,
  `cad1` text NOT NULL,
  `cad2` text NOT NULL,
  `cad3` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created by Sangkan';

--
-- Dumping data for table `2011infokios`
--

INSERT INTO `2011infokios` (`id`, `kios`, `admin`, `tglkirim`, `judulberita`, `deskripsi`, `photoberita`, `cad1`, `cad2`, `cad3`) VALUES
(5453, 'UPTPK SITUBONDO', 'nitha', '06/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Bangunan/Meubeller di Desa Blimbing Kec. Besuki', 'Penutupan Pelatihan Berbasis Masyarakat Kejuruan Meubeller yang dilaksanakan pada hari selasa tanggal 31 des 2013. pada kesempatan ini dihadiri oleh camat besuki yang juga berkenan menutup secara resmi pelatihan tersebut. diharapkan dengan adanya pelatihan ini peserta dapat menciptakan lapangan kerja mandiri di lingkungan sekitar.', 'img_6930.jpg', '', '', ''),
(5454, 'UPTPK SITUBONDO', 'nitha', '06/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Bangunan /Meubeller di Desa Blimbing Kec. Besuki Kab. Situbondo', 'Penutupan Pelatihan Berbasis Masyarakat Kejuruan Meubeller yang dilaksanakan pada hari selasa tanggal 31 des 2013. pada kesempatan ini dihadiri oleh camat besuki yang juga berkenan menutup secara resmi pelatihan tersebut. diharapkan dengan adanya pelatihan ini peserta dapat menciptakan lapangan kerja mandiri di lingkungan sekitar.', 'img_6937.jpg', '', '', ''),
(5455, 'UPTPK SITUBONDO', 'nitha', '06/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Bangunan/Meubeller di Desa Blimbing Kec. Besuki Kab. Situbondo', 'Penutupan Pelatihan Berbasis Masyarakat Kejuruan Meubeller yang dilaksanakan pada hari selasa tanggal 31 des 2013. pada kesempatan ini dihadiri oleh camat besuki yang juga berkenan menutup secara resmi pelatihan tersebut. diharapkan dengan adanya pelatihan ini peserta dapat menciptakan lapangan kerja mandiri di lingkungan sekitar.', 'img_6928.jpg', '', '', ''),
(5456, 'UPTPK SUMENEP', 'Rina Fitri S', '07/01/2014', 'STUDY BANDING KIOS 3IN1 BLKI MAKASSAR KE UPTPK SUMENEP', '05 DESEMBER 2013 STUDY BANDING KIOS 3IN1 BLKI MAKASSAR KE KIOS 3IN1 UPTPK SUMENEP DALAM HAL KUNJUNGAN KERJA DAN PENEMPATAN', 'img_1374.jpg', '', '', ''),
(5457, 'UPTPK SURABAYA', 'Esa Insani', '10/01/2014', 'Recrutmen alumni siswa UPT Pelatihan kerja surabaya dengan perusahaan', 'Recrutmen alumni siswa UPT Pelatihan kerja surabaya dengan perusahaan', 'img_6306 (300 x 200).jpg', '', '', ''),
(5458, 'UPTPK SURABAYA', 'Esa Insani', '10/01/2014', 'Uji Kompetensi', 'Uji Kompetensi kejuruan Automotif', 'img_8540 (300 x 200).jpg', '', '', ''),
(5459, 'UPTPK SURABAYA', 'Esa Insani', '10/01/2014', 'Uji Kompetensi', 'Uji Kompetensi kejuruan Automotif sepeda motor UPT Pelatihan kerja surabaya', 'img_8550 (300 x 200).jpg', '', '', ''),
(5460, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Sepeda motor dan Menjahit di Kec. Sumbersuko Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Sepeda motor di desa petahunan dan menjahit di desa kebonsari kec. sumbersuko kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh camat yang diwakili oleh sekcam sumbersuko beserta ketua tim penggerak PKK sekaligus ibu camat, dan 16 peserta masing-masing kejuruan. ibu herita selaku tokoh masyarakat juga berkenan memberikan sambutan kepada para peserta pelatihan. diharapkan dengan adanya pelatihan ini mereka dapat mengembangkan usaha mandiri dan lapangan kerja.', 'img_6997.jpg', '', '', ''),
(5461, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Sepeda motor dan Menjahit di Kec. Sumbersuko Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Sepeda motor di desa petahunan dan menjahit di desa kebonsari kec. sumbersuko kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh camat yang diwakili oleh sekcam sumbersuko beserta ketua tim penggerak PKK sekaligus ibu camat, dan 16 peserta masing-masing kejuruan. ibu herita selaku tokoh masyarakat juga berkenan memberikan sambutan kepada para peserta pelatihan. diharapkan dengan adanya pelatihan ini mereka dapat mengembangkan usaha mandiri dan lapangan kerja.', 'img_7006.jpg', '', '', ''),
(5462, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Sepeda motor dan Menjahit di Kec. Sumbersuko Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Sepeda motor di desa petahunan dan menjahit di desa kebonsari kec. sumbersuko kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh camat yang diwakili oleh sekcam sumbersuko beserta ketua tim penggerak PKK sekaligus ibu camat, dan 16 peserta masing-masing kejuruan. ibu herita selaku tokoh masyarakat juga berkenan memberikan sambutan kepada para peserta pelatihan. diharapkan dengan adanya pelatihan ini mereka dapat mengembangkan usaha mandiri dan lapangan kerja.', 'img_7027.jpg', '', '', ''),
(5463, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Sepeda motor dan Menjahit di Kec. Sumbersuko Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Sepeda motor di desa petahunan dan menjahit di desa kebonsari kec. sumbersuko kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh camat yang diwakili oleh sekcam sumbersuko beserta ketua tim penggerak PKK sekaligus ibu camat, dan 16 peserta masing-masing kejuruan. ibu herita selaku tokoh masyarakat juga berkenan memberikan sambutan kepada para peserta pelatihan. diharapkan dengan adanya pelatihan ini mereka dapat mengembangkan usaha mandiri dan lapangan kerja.', 'img_7054(1).jpg', '', '', ''),
(5464, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Processing Di Kec. Jatiroto Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Processing di kec. Jatiroto kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh kepala UPT pelatihan kerja situbondo atau yang mewakili. bapak camat jatiroto juga berkenan menutup secara resmi pelatihan tersebut.', 'img_7089.jpg', '', '', ''),
(5465, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Processing Di Kec. Jatiroto Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Processing di kec. Jatiroto kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh kepala UPT pelatihan kerja situbondo atau yang mewakili. bapak camat jatiroto juga berkenan menutup secara resmi pelatihan tersebut.', 'img_7091.jpg', '', '', ''),
(5466, 'UPTPK SITUBONDO', 'nitha', '13/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Processing Di Kec. Jatiroto Kab. Lumajang', 'Penutupan pelatihan MTU Kejuruan Processing di kec. Jatiroto kab. lumajang yang dilaksanakan pada hari jumat tanggal 10 januari 2014. pada kesempatan ini di hadiri oleh kepala UPT pelatihan kerja situbondo atau yang mewakili. bapak camat jatiroto juga berkenan menutup secara resmi pelatihan tersebut.', 'img_7104.jpg', '', '', ''),
(5467, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7737.jpg', '', '', ''),
(5468, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7777.jpg', '', '', ''),
(5469, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7779.jpg', '', '', ''),
(5470, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7782.jpg', '', '', ''),
(5471, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7783.jpg', '', '', ''),
(5472, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7785.jpg', '', '', ''),
(5473, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7787.jpg', '', '', ''),
(5474, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7788.jpg', '', '', ''),
(5475, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7791.jpg', '', '', ''),
(5477, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', 'dsc_7795.jpg', '', '', ''),
(5478, 'UPTPK PONOROGO', 'nurul listiana', '15/01/2014', 'Peresmian Gedung UPT PK Ponorogo', 'Acara peresmian gedung UPT PK Ponorogo diselenggarakan pada hari sabtu tanggal 11 januari 2014 yang diresmikan oleh : Bpk. Dr. Edi Purwinarto, M.Si selaku Plt. Kadisnakertransduk Prov.Jatim dan Bpk. Soegiri Sancoko, SE Selaku Ketua Komisi E DPRD Prov.Jatim dengan hiburan pagelaran wayang kulit.', '', '', '', ''),
(5479, 'UPTPK SURABAYA', 'Esa Insani', '15/01/2014', 'Uji Kompetensi', 'Uji Kompetensi kejuruan Mesin Logam UPT Pelatihan Kerja Surabaya', 'img_8541 (300 x 200).jpg', '', '', ''),
(5480, 'UPTPK SURABAYA', 'Esa Insani', '15/01/2014', 'Uji Kompetensi', 'Uji Kompetensi Kejuruan Las UPT Pelatihan Kerja Surabaya', 'img_8101 (600 x 400).jpg', '', '', ''),
(5481, 'BBPLKDN BANDUNG', 'yusnita karolina', '16/01/2014', 'Kunjungan SMK 1 Terusan Nunyai Lampung Tengah', 'Pada hari kamis tanggal 16 januari 2014 SMK 1 terusan Nunyai Lampung tengah mengunjungi BBPLKDN Bandung sebagai kegiatan dari SMK tersebut dalam memperkenalkan tentang keadaan dan kondisi yang sebenarnya pada dunia Industri dan kegiatan Sosialisasi tentang BBPLKDN Bandung', 'edit1a(1).jpg', '', '', ''),
(5482, 'BBPLKDN BANDUNG', 'yusnita karolina', '16/01/2014', 'Kunjungan SMK 1 Terusan Nunyai Lampung Tengah', 'Pada hari kamis tanggal 16 januari 2014 SMK 1 terusan Nunyai Lampung tengah mengunjungi BBPLKDN Bandung sebagai kegiatan dari SMK tersebut dalam memperkenalkan tentang keadaan dan kondisi yang sebenarnya pada dunia Industri dan kegiatan Sosialisasi tentang BBPLKDN Bandung', 'edit2a.jpg', '', '', ''),
(5483, 'UPTPK SURABAYA', 'Esa Insani', '20/01/2014', 'POM BENSIN UPT PELATIHAN KERJA SURABAYA', 'Penggunaan pom bensin UPT PK Surabaya', 'img_8261 (300 x 200).jpg', '', '', ''),
(5484, 'UPTPK SURABAYA', 'Esa Insani', '20/01/2014', 'POM BENSIN UPT PELATIHAN KERJA SURABAYA', 'Penggunaan Pom bensin', 'img_8264 (300 x 200).jpg', '', '', ''),
(5485, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/01/2014', 'Uji Kompetensi (UJK) Teknologi Mekanik', 'Kegiatan Pra UJK kejuruan Teknologi Mekanik Las Listrik dilaksanakan oleh peserta alumni peserta pelatihan las listrik. Sejumlah 37 peserta dengan harapan mampu bersaing di dunia kerja dengan hasil kompetensi ujian yang telah diikuti.', 'pra ujk las (jan \'14).jpg', '', '', ''),
(5486, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/01/2014', 'Uji Kompetensi (UJK) Teknologi Mekanik', '-', 'ujk las listrik 2 (jan \'14).jpg', '', '', ''),
(5487, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/01/2014', 'Uji Kompetensi (UJK) Teknologi Mekanik', 'Tes UJK Las Listrik diuji oleh asesor UPT Pelatihan Kerja Tuban Bapak Supardi, ST, dan Harjono, SPd.', 'ujk las listrik 1 (jan \'14).jpg', '', '', ''),
(5491, 'BLKI PAPUA', 'Andri Gunawan', '22/01/2014', 'BALAI LATIHAN KERJA INDUSTRI PROV. PAPUA GELAR SYUKURAN MASUKI TAHUN KERJA BARU', 'Pejabat Disnakerduk Prov. Papua, PNS di lingkungan BLKI Prov. Papua bersama Pensiunan serta Warga Komp. BLK saat menghadiri Acara Syukuran Balai Latihan Kerja Industri Prov. Papua.', 'dscn3842.jpg', '', '', ''),
(5492, 'UPTPK SITUBONDO', 'nitha', '22/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Pembuatan Sepatu Di Desa Kilensari Kec. Panarukan', 'Penutupan pelatihan MTU Kejuruan Pembuatan sepatu di Desa Kilensari kec. Panarukan kab. Situbondo yang dilaksanakan pada hari ini Rabu tanggal 22 januari 2014. pada kesempatan ini di hadiri oleh camat panarukan atau yang mewakili juga berkenan memberikan pengarahan kepada peserta pelatihan tersebut. dengan adanya pelatihan ini diharapkan dapat meningkatkan lapangan kerja di lingkungan sekitar.', 'img_7191.jpg', '', '', ''),
(5493, 'UPTPK SITUBONDO', 'nitha', '22/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Pembuatan sepatu di Desa Kilensari Kec. Panarukan', 'Penutupan pelatihan MTU Kejuruan Pembuatan sepatu di Desa Kilensari kec. Panarukan kab. Situbondo yang dilaksanakan pada hari ini Rabu tanggal 22 januari 2014. pada kesempatan ini di hadiri oleh camat panarukan atau yang mewakili juga berkenan memberikan pengarahan kepada peserta pelatihan tersebut. dengan adanya pelatihan ini diharapkan dapat meningkatkan lapangan kerja di lingkungan sekitar.', 'img_7200.jpg', '', '', ''),
(5494, 'UPTPK SITUBONDO', 'nitha', '22/01/2014', 'Penutupan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Pembuatan sepatu di Desa Kilensari Kec. Panarukan', 'Penutupan pelatihan MTU Kejuruan Pembuatan sepatu di Desa Kilensari kec. Panarukan kab. Situbondo yang dilaksanakan pada hari ini Rabu tanggal 22 januari 2014. pada kesempatan ini di hadiri oleh camat panarukan atau yang mewakili juga berkenan memberikan pengarahan kepada peserta pelatihan tersebut. dengan adanya pelatihan ini diharapkan dapat meningkatkan lapangan kerja di lingkungan sekitar.', 'img_7192.jpg', '', '', ''),
(5495, 'BLKI PAPUA', 'Andri Gunawan', '22/01/2014', 'BALAI LATIHAN KERJA INDUSTRI PROV. PAPUA GELAR SYUKURAN MASUKI TAHUN KERJA BARU', 'Kepala BLKI, Djoni Naa, SE. M.Si (nomor 2 dari kanan) bersama Pejabat di lingkungan Disnakerduk dan BLKI prov. Papua saat hendak mengikuti sesi jabat tangan.', 'dscn3851.jpg', '', '', ''),
(5496, 'BLKI PAPUA', 'Andri Gunawan', '22/01/2014', 'BALAI LATIHAN KERJA INDUSTRI PROV. PAPUA GELAR SYUKURAN MASUKI TAHUN KERJA BARU', 'Sesi Jabat Tangan Kepala BLKI, bersama Pejabat di lingkungan Disnakerduk dan BLKI prov. Papua dengan Pensiunan, warga Komp. BLK beserta Staf Balai Latihan Kerja Prov. Papua.', 'dscn3857.jpg', '', '', ''),
(5497, 'BLKI PAPUA', 'Andri Gunawan', '22/01/2014', 'BALAI LATIHAN KERJA INDUSTRI PROV. PAPUA GELAR SYUKURAN MASUKI TAHUN KERJA BARU', 'Kepala BLKI Prov. Papua, Djoni Naa, SE. M.Si saat menyampaikan Kesan dan Pesan pada Acara Syukuran Balai Latihan Kerja Industri.', 'dscn3843.jpg', '', '', ''),
(5498, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7138.jpg', '', '', ''),
(5499, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7142.jpg', '', '', ''),
(5500, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7163.jpg', '', '', ''),
(5501, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7165.jpg', '', '', ''),
(5502, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7141.jpg', '', '', ''),
(5503, 'UPTPK SITUBONDO', 'nitha', '23/01/2014', 'Kegiatan Peserta Pelatihan Batako di UPT Pelatihan Kerja Situbondo', 'kegiatan para peserta pelatihan batako yang dilaksanakan di UPT Pelatihan Kerja Situbondo yang di bimbing langsung oleh Bpk Arif selaku instruktur kejuruan tersebut.', 'img_7164.jpg', '', '', ''),
(5504, 'UPTPK SURABAYA', 'Esa Insani', '27/01/2014', 'INTERVIEW PT. BESTOPIA, PASURUAN', 'perekrutan perusahaan batu bara dengan alumni UPT Pelatihan Kerja Surabaya', 'img_8132 (300 x 200).jpg', '', '', ''),
(5505, 'UPTPK SURABAYA', 'Esa Insani', '27/01/2014', 'UJK Las', 'Uji Kompetensi kejuruan Las UPT Pelatihan Kerja Surabaya', 'img_8361 (300 x 200).jpg', '', '', ''),
(5511, 'BBPLKDN BANDUNG', 'yusnita karolina', '28/01/2014', 'Rekrutmen calon karyawan GRAMEDIA GROUP OF PRINTING', 'pada hari selasa tanggal 28/01/2014 telah dilakukan proses rekrutmen untuk calon karyawan GRAMEDIA GROUP OF PRINTING yang dilaksanakan di aula gedung BBPLKDN Bandung dan secara resmi dibuka oleh bapak Drs. Wawan Hartawan selaku perwakilan dari Manajemen BBPLKDN Bandung', 'ok edit.jpg', '', '', ''),
(5512, 'BBPLKDN BANDUNG', 'yusnita karolina', '28/01/2014', 'Rekrutmen calon karyawan GRAMEDIA GROUP OF PRINTING', 'pada hari selasa tanggal 28/01/2014 telah dilakukan proses rekrutmen untuk calon karyawan GRAMEDIA GROUP OF PRINTING yang dilaksanakan di aula gedung BBPLKDN Bandung dan secara resmi dibuka oleh bapak Drs. Wawan Hartawan selaku perwakilan dari Manajemen BBPLKDN Bandung', 'ok2 edit.jpg', '', '', ''),
(5514, 'UPTPK SUMENEP', 'Melly Herawati', '29/01/2014', 'PELUANG KARIR DI PT INDOMARCO PRISMATAMA SURABAYA (07 FEBRUARI 2014)', 'PT INDOMARCO PRISMATAMA SURABAYA MEMBUKA PELUANG KARIR DI WILAYAH MADURA. BAGI ANDA YANG BERMINAT SEGERA DAFTARKAN DIRI ANDA!!', 'scan0035 (copy).jpg', '', '', ''),
(5515, 'UPTPK JOMBANG', 'IFA', '30/01/2014', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG DIADAKAN DI AULA UPT PELATIHAN KERJA JOMBANG PADA TANGGAL 28 JANUARI 2014. PT. DHARMA PERKASA GEMILANG MERUPAKAN PERUSAHAAN KERAMIK YANG BERADA DI NGORO INDUSTRI PERSADA MOJOKERTO. PESERTA TES MENCAPAI 52 ORANG. SELEKSI YANG DIADAKAN MELIPUTI TES PSIKOLOGI SERTA TES KESEHATAN.', 'img_0011.jpg', '', '', ''),
(5516, 'UPTPK JOMBANG', 'IFA', '30/01/2014', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG DIADAKAN DI AULA UPT PELATIHAN KERJA JOMBANG PADA TANGGAL 28 JANUARI 2014. PT. DHARMA PERKASA GEMILANG MERUPAKAN PERUSAHAAN KERAMIK YANG BERADA DI NGORO INDUSTRI PERSADA MOJOKERTO. PESERTA TES MENCAPAI 52 ORANG. SELEKSI YANG DIADAKAN MELIPUTI TES PSIKOLOGI SERTA TES KESEHATAN.', 'img_0017.jpg', '', '', ''),
(5517, 'UPTPK JOMBANG', 'IFA', '30/01/2014', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG', 'REKRUITMENT PT. DHARMA PERKASA GEMILANG DIADAKAN DI AULA UPT PELATIHAN KERJA JOMBANG PADA TANGGAL 28 JANUARI 2014. PT. DHARMA PERKASA GEMILANG MERUPAKAN PERUSAHAAN KERAMIK YANG BERADA DI NGORO INDUSTRI PERSADA MOJOKERTO. PESERTA TES MENCAPAI 52 ORANG. SELEKSI YANG DIADAKAN MELIPUTI TES PSIKOLOGI SERTA TES KESEHATAN.', 'img_0026.jpg', '', '', ''),
(5518, 'BLKI PAPUA', 'Andri Gunawan', '04/02/2014', 'PROF. C. VOLKER DARI D.W UNIVERSITY PNG KUNJUNGI BLKI PROVINSI PAPUA', 'Prof. C. Volker dari Divine Word University Maddang Papua Nugini ( PNG ) didampingi Kadis Nakerduk Prov. Papua (Drs. Yan Piet Rawar), Kepala BLKI Prov Papua (Djoni Naa, SE. M.Si) beserta Kepala Seksi dan Tenaga Instruktur saat mengunjungi salah satu tempat pelatihan pada Balai Latihan Kerja Industri Prov. Papua.', '20140128_110919.jpg', '', '', ''),
(5519, 'BLKI PAPUA', 'Andri Gunawan', '04/02/2014', 'PROF. C. VOLKER DARI D.W UNIVERSITY PNG KUNJUNGI BLKI PROVINSI PAPUA', 'Prof. C. Volker dari Divine Word University Maddang PNG, Kadis Nakerduk Prov. Papua Drs. Yan Piet Rawar bersama Kepala Seksi dan Tenaga Instruktur BLKI Prov. Papua saat sesi foto bersama.', '20140128_104949.jpg', '', '', ''),
(5521, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '04/02/2014', 'PEMBUKAAN PENDAFTARAN PELATIHAN GRATIS', 'Bojonegoro Kiosthreeinone PEMBUKAAN PENDAFTARAN PELATIHAN GRATIS DI BLK BOJONEGORO / UPTPK BOJONEGORO KEJURUAN : - KOMPUTER - SERVICE SEPEDA MOTOR - TEKNIK PENDINGIN ( AC ) - PROCESSING PERSYARATAN : FOTO 4X6 4 LBR, F.COPY IJASAH TERAKHIR 1 LEMBAR PENDAFTARAN : 03 s/d 10 FEBRUARI 2014 DI KIOS 3IN1 UPTPK BOJONEGORO/BLK BOJONEGORO TEST SELEKSI : 12 FEBRUARI 2014 PENGUMUMAN HASIL TEST : 18 FEBRUARI 2014 DAFTAR ULANG : 19 S/D 21 FEBRUARI 2014 MASUK PELATIHAN : 24 FEBRUARI 2014 TEST SELEKSI : 12 FEBRUARI 2014 PUKUL : 09.00 WIB TEMPAT : AULA UPTPK BOJONEGORO / BLK BOJONEGORO MEMAKAI PAKAIAN ATASAN PUTIH (BUKAN KAOS), BAWAHAN GELAP, BERSEPATU DAN MEMBAWA ALAT TULIS.', 'pengumuman fb 1 [1600x1200].jpg', '', '', ''),
(5522, 'BLKI SEMARANG', 'S. Edy Witoko', '11/02/2014', 'PELATIHAN DI BLKI SEMARANG TAHUN 2014', 'TELAH DIBUKA PENDAFTARAN PELATIHAN KETRAMPILAN DI BLKI SEMARANG TAHUN 2014 BAGI PENCAKER DENGAN PERSYARATAN : PRIA & WANITA USIA MINIMAL 18 TAHUN........... AYOOO BERGABUNGLAH DENGAN KAMI BLKI SEMARANG YANG PUNYA MISI & VISI : MENCETAK PESERTA PELATIHAN YANG TRAMPIL & KOMPETEN', 'q(1).jpg', '', '', ''),
(5523, 'BBPLKDN BANDUNG', 'yusnita karolina', '17/02/2014', 'Program Pelatihan Berbasis Kompetensi 2014', 'BBPLKDN Membuka pendaftaran untuk Program Pelatihan Berbasis Kompetensi 2014 (PBK) yang di mulai dari bulan Februari 2014', 'flyer2ok3.jpg', '', '', ''),
(5524, 'BBLKI SERANG', 'NUNI', '05/02/2014', 'TELAH DIBUKA PENDAFTARAN PELATIHAN DI BBLKI SERANG (GATISSS..)', 'TELAH DIBUKA PELATIHAN DI Balai Besar Latihan Kerja Industri (BBLKI) serang BBLKI Serang membuka Pelatihan Berbasis Kompetensi (PBK) biaya Pelatihan Gratis dan Pendaftaran Gelombang 1 sd 16 Februari 2014 Kesempatan mengikuti program pelatihan ini terbuka untuk Masyarakat umum di wilayah Banten dan sekitarnya untuk Gelombang 1 BBLKI Serang membuka Pelatihan : I.KEJURUAN : A. TEKNOLOGI MEKANIK (TEKMEK) 1. MATERIAL TESTING 2. OPERATOR BUBUT DASAR 3. OPERATOR CNC 4. OPERATOR MESIN BUBUT FRAIS DASAR 5. DRAFTER MESIN B. LAS 1. SMAW 2. FCAW 3G 3. SMAW 3G 4. GTAW C. LISTRIK 1. INSTALASI LISTRIK 2. TEKNISI AUDIO 3. LISTRIK INDUSTRI D.TEKNOLOGI INFORMASI (TI) 1. PROFESIONAL OFFICE 2. TEKNIK KOMPUTER & JARINGAN 3. WEB DESAIGN E. OTOMOTIF 1. ETU KONVENSIONAL (Service Mobil Karburator) 2. SEPEDA MOTOR MONTIR JUNIOR 3. ETU DIESEL (Service Mobil Diesel) F. MEKATRONIK 1. OPERATOR OTOMASI INDUSTRI G. MENJAHIT 1. MENJAHIT PAKAIAN WANITA DEWASA & ANAK 2. MENJAHIT PAKAIAN WANITA DEWASA I. PERSYARATAN PENDAFTARAN : 1. Laki-laki / perempuan 2. Foto copy ijazah SLTA atau yang sederajat 3. Foto copy KTP 4. Pas foto berwarna ukuran 3x4 = 4 lembar (Backgraund Merah) 5. Untuk Menjahit Min. Pendidikan SMP/Sederajat dan Usia Maks. 45 Tahun 6. Untuk Sepeda Motor Min. Pendidikan SMP/Sederajat dan Usia Maks. 25 Tahun Tempat Pendaftaran: Gedung Kios 3in1 BBLKI Serang Jln.Raya Pandeglang Km. 3 Serang Banten Informasi : Website : www.kios3in1.net www.bblkiserang.binalattas.depnakertrans.go.id Contact Person : Kantor : 0254- 200160 / 202735 Nuni : 0877 7170 9911 Wida : 0878 7752 2409', '38015 bblki brosur_bys 2014 gel1_rev.jpg', '', '', ''),
(5525, 'BLKI PADANG', 'sugianto', '06/02/2014', 'Mantan siswa BLKI Padang', 'Salah seoarang mantan siswa BLKI yang diterima kerja di Suzuki', 'siswa blki.jpg', '', '', ''),
(5526, 'UPTPK JEMBER', 'IMANIAR AGUSTINA', '07/02/2014', 'Kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 UPT Pelatihan Kerja Jember di Kabupaten Lumajang', 'Kegiatan sosialisasi melibatkan beberapa dinas dan instansi terkait. Partisipan Kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 Kabupaten Jember antara lain melibatkan Badan Pemberdayaan Masyarakat (BAPEMAS) Kabupaten Lumajang, Dinas Pendidikan Nasional Kabupaten Lumajang dan Dinas Tenaga kerja dan transmigrasi Kabupaten Lumajang. Badan Pemberdayaan Masyarakat (BAPEMAS) Kabupaten Jember sebagai instasi yang membawahi kelompok PNPM Mandiri Pedesaan.', 'dsc02033.jpg', '', '', ''),
(5527, 'UPTPK JEMBER', 'IMANIAR AGUSTINA', '07/02/2014', 'Kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 UPT Pelatihan Kerja Jember di Kabupaten Lumajang', 'Unit Pelaksana Teknis Pelatihan Kerja Jember (UPT-PK Jember) yang merupakan Unit Pelaksana Teknis Dinas (UPTD) dari Dinas Tenaga Kerja Transmigrasi dan Kependudukan Provinsi Jawa Timur mengemban tugas untuk memberikan kebutuhan ketrampilan yang dipersyaratkan didunia usaha. Langkah yang konkrit guna menyebarkan informasi kegiatan UPT Pelatihan Kerja salah satunya adalah melalui kegiatan sosialisasi.', 'dsc02025.jpg', '', '', ''),
(5528, 'UPTPK JEMBER', 'IMANIAR AGUSTINA', '07/02/2014', 'Kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 UPT Pelatihan Kerja Jember di Kabupaten Lumajang', 'Kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 Kabupaten Jember dihadiri sebanyak 80 orang peserta. Materi dalam kegiatan Sosialisasi Program Pelatihan dan Pemagangan Jepang Tahun 2013 disampaikan oleh 3 pemateri. Kepala Seksi Pelatihan dan Sertifikasi UPT Pelatihan Kerja Jember, menjelaskan materi tentang pelaksanaan kegiatan pelatihan MTU, Pelatihan Berbasis Kompetensi (PBK), Swadana dan pelaksanaan Uji Kompetensi. Bandu Tramiadji selaku pemateri II menjelaskan materi tentang Pemagangan di Jepang dan penempatan tenaga kerja di Korea. Tenaga Admin/CSO Kios 3in1 juga turut serta menyampaikan informasi mengenai Bursa Kerja dan Layanan online.', 'dsc02044.jpg', '', '', ''),
(5529, 'BLKI PADANG', 'sugianto', '11/02/2014', 'Siswa Bedcover', 'Salah seorang siswa Menjahit tahun 2013 yang sudah membuka usaha mandiri Pembuatan Bed Cover', 'siswa yg mandiri.jpg', '', '', ''),
(5530, 'BBPLKDN BANDUNG', 'yusnita karolina', '11/02/2014', 'Kunjungan SMK Islam Cipasung Tasikmalaya', 'pada hari selasa tanggal 11 Februari 2014,BBPLKDN Bandung mendapat kunjungan dari SMK Islam Cipasung Tasikmalaya sebagai sosialisasi siswa terhadap Balai dan industri.Kegiatan ini diterima dengan baik oleh Kasi Pemberdayaan BBPLKDN Bandung Bapak Drs. Wawan Hartawan dan Bapak FX Iwan Eka Irawanto, S.Pd selaku perwakilan dari manajemen.', 'kunjungan.jpg', '', '', ''),
(5531, 'BBPLKDN BANDUNG', 'yusnita karolina', '11/02/2014', 'Kunjungan SMK Islam Cipasung Tasikmalaya', 'pada hari selasa tanggal 11 Februari 2014,BBPLKDN Bandung mendapat kunjungan dari SMK Islam Cipasung Tasikmalaya sebagai sosialisasi siswa terhadap Balai dan industri.Kegiatan ini diterima dengan baik oleh Kasi Pemberdayaan BBPLKDN Bandung Bapak Drs. Wawan Hartawan dan Bapak FX Iwan Eka Irawanto, S.Pd selaku perwakilan dari manajemen.', 'kunjungan 3.jpg', '', '', ''),
(5532, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5152.jpg', '', '', ''),
(5533, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5153.jpg', '', '', ''),
(5534, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5154.jpg', '', '', ''),
(5535, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5155.jpg', '', '', ''),
(5536, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5156.jpg', '', '', ''),
(5537, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5157.jpg', '', '', ''),
(5538, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5158.jpg', '', '', ''),
(5539, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5159.jpg', '', '', ''),
(5540, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5163.jpg', '', '', ''),
(5541, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5165.jpg', '', '', ''),
(5542, 'UPTPK PONOROGO', 'nurul listiana', '13/02/2014', 'Pembukaan Pelatihan Kejuruan Processing', 'Pembukaan Pelatihan Berbasis Kompetensi Kejuruan Processing di Ds. Pojok, Kawedanan Magetan, Acara Dihadiri oleh Ka UPT PK Ponorogo, Camat Kawedanan, Perwakilan dari Dinsosnakertrans Kab. Magetan, dan Kepala Desa Pojok.', 'img_5166.jpg', '', '', ''),
(5543, 'BLK KAB. PASURUAN', 'yudha', '13/02/2014', 'Pembangunan Gedung BLK Pasuruan', 'Pembangunan BLK Pasuruan dimulai sejak tahun 2012', 'dsc02330 [640x480].jpg', '', '', ''),
(5544, 'BLK KAB. PASURUAN', 'yudha', '13/02/2014', 'Guest House', 'Pembangunan Gedung Guest House', 'dsc02354 [640x480].jpg', '', '', ''),
(5545, 'BLK KAB. PASURUAN', 'yudha', '13/02/2014', 'Kunjungan Kerja', 'Kunjungan kerja peserta diklat pengantar keja tingkat nasional.', 'dsc02719 [640x480].jpg', '', '', ''),
(5546, 'BBLKI SERANG', 'NUNI', '13/02/2014', 'Penandatanganan Kontrak OJT Alumni BBLKI Serang dengan PT. EDS Manufacturing Indonesia', 'Selamat kepada 21 orang lulusan BBLKI Serang yang hari ini menandatangani kontrak OJT dengan PT. EDS Manufacturing Indonesia. Diantaranya Kejuruan : 1. Profesional Office 2 Orang 2. Design Grafis 1 Orang 3. Drafter 3 Orang 4. Las 6 Orang 5. Instalasi Listrik 2 Orang 6. Otomasi 3 Orang 7. Material Testing 1 Orang 8. Teknisi Komputer 3 Orang', 'dadad.jpg', '', '', ''),
(5547, 'BLK KAB. PASURUAN', 'yudha', '13/02/2014', 'Pelatihan Menjahit', 'Selama tahun 2013 telah dilaksakan program pelatihan menjahit sebanyak 4 angkatan dan untuk pelatihan bordir sebanyak 4 angkatan. Masing-masing program pelatihan, untuk setiap angkatan dilaksanakan selama 30 hari kerja dan setiap hari 8 jam pelajaran. Untuk tahun 2014 direncanakan sebanyak 22 pelatihan yang terdiri dari 4 jurusan. Antara lain menjahit, bordir, otomotif roda 2, dan pelatihan elektronika. Sedangkan untuk jurusan yang lainnya yaitu untuk jurusan TI, Tekmek, otomotif roda 4, bangunan dan jurusan listrik masing dalam persiapan kurikulum maupun prasarananya (peralatan).', 'dsc02913 [640x480].jpg', '', '', ''),
(5548, 'BBPLKDN BANDUNG', 'yusnita karolina', '13/02/2014', 'Rekruitmen alumni MEISTER untuk dietempatkan di PT MSE', 'Pengarahan oleh pihak PT Multi Sinergi Ekatama dalam proses rekruitmen alumni MEISTER oleh PT MSE untuk ditempatkan di Kalimantan.(Kamis 13/02/2014)', 'ok.jpg', '', '', ''),
(5549, 'UPTPK SUMENEP', 'Rina Fitri S', '14/02/2014', 'SELEKSI CALON KARYAWAN PT INDOMARCO PRISMATAMA SURABAYA DI UPT PK SUMENEP (07 FEBRUARI 2014)', 'TANGGAL 07 FEBRUARI 2014, SETELAH DIADAKAN SELEKSI CALON KARYAWAN INDOMARET DI AULA UPT PK SUMENEP, DARI 24 ORANG PENCAKER YANG MENDAFTAR, 9 ORANG PESERTA DINYATAKAN LULUS. PESERTA YANG LULUS DIBERIKAN PENGARAHAN OLEH BAPAK SIGIT SELAKU HRD.', '20140207_104156.jpg', '', '', ''),
(5550, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '15/02/2014', 'Training Petugas Kios 3in1', 'Sehubungan dengan akan diresmikannya BLK dan KIOS3in1 Kab. Pasuruan pada tanggal 5 Maret 2014 nanti maka Pemerintah Kab. Pasuruan mendatangkan staff untuk mentraining para petugas Kios 3in1 guna mempersiapkan pelayanan di Kios 3in1 nanti.', 'dsc03653 [640x480].jpg', '', '', ''),
(5551, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '18/02/2014', 'PENGUMUMAN', 'PENGUMUMAN HASIL TEST SELEKSI TGL . 12 FEBRUARI 2014 KEJURUAN SEPEDA MOTOR DI UPTPK BOJONEGORO', 'motor 1 [1600x1200].jpg', '', '', ''),
(5552, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '18/02/2014', 'PENGUMUMAN', 'PENGUMUMAN HASIL TEST SELEKSI TGL . 12 FEBRUARI 2014 KEJURUAN KOMPUTER DI UPTPK BOJONEGORO', 'komputer - 1 [1600x1200].jpg', '', '', ''),
(5553, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '18/02/2014', 'PENGUMUMAN', 'PENGUMUMAN HASIL TEST SELEKSI TGL . 12 FEBRUARI 2014 KEJURUAN PROCESSING DI UPTPK BOJONEGORO', 'processing - 1. [1600x1200].jpg', '', '', ''),
(5555, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '18/02/2014', 'PENGUMUMAN', 'PENGUMUMAN HASIL TEST SELEKSI TGL . 12 FEBRUARI 2014 KEJURUAN TEKNIK PENDINGIN / AC DI UPTPK BOJONEGORO', 'ac - 1 [1600x1200].jpg', '', '', ''),
(5557, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/02/2014', 'PELATIHAN MULTIMEDIA', 'Telah dibuka pelatihan kejuruan Multimedia dengan siswa PSG dari sekolah SMK Sukodadi kelas XII', 'img_8671 (copy).jpg', '', '', ''),
(5558, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/02/2014', 'PELATIHAN KEJURUAN MULTIMEDIA', 'Siswa PSG kelas XII diwajibkan mampu menguasai materi sesuai dengan kejuruan yang dipilih yaitu multimedia yang berkaitan dengan cara bagaimana proses membuat pamflet, brosur, efek foto dan kartu nama sehingga siap memasuki dunia kerja maupun wirausaha.', 'img_8672 (copy).jpg', '', '', ''),
(5559, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/02/2014', 'KEGIATAN SOSIALISASI', 'Kegiatan sosialisasi dan pengenalan kejuruan baru yaitu Multimedia dan Bahasa Inggris yang dilaksanakan di aula UPT Pelatihan Kerja Tuban dengan mengundang beberapa sekolah kejuruan di Tuban dan sekitarnya. Antara lain SMK Negeri 1 Tuban, SMK Abdi Negara, Primagama, SMK Taruna Jaya Prawira, SMK YPM 12 Tuban,', 'img_8644 (copy).jpg', '', '', ''),
(5560, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '20/02/2014', 'KEGIATAN SOSIALISASI', 'Pengenalan bengkel kejuruan pelatihan.', 'img_8655 (copy).jpg', '', '', ''),
(5561, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '21/02/2014', 'PEMBUKAAN PENDAFTARAN PELATIHAN GRATIS', 'PEMBUKAAN PENDAFTARAN PELATIHAN GRATIS DI BLK BOJONEGORO / UPTPK BOJONEGORO PERSYARATAN : 1. Pria / wanita sehat jasmani dan rohani 2. Pendidikan Min SLTP 3. Mengisi Formulir Pendaftaran 4. Menyerakan FOTO berwarna 4X6 sebanyak 4 LBR, 5. Menyerahkan F.COPY IJASAH TERAKHIR 1 LEMBAR TEMPAT PENDAFTARAN : KIOS 3IN1 UPTPK BOJONEGORO/ BLK BOJONEGORO Senin s/D Jumat Pkl. 08.00 s/d 14.00 WiB PENDAFTARAN GELOMBANG I DUBUKA SAMPAI DENGAN AWAL BULAN APRIL 2014', 'untitled-1 [1600x1200].jpg', '', '', ''),
(5563, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '24/02/2014', 'LOWONGAN KERJA JACOBIS', 'PERUSAHAAN DIBIDANG CONSUMER GOOD YANG SUDAH DIKENAL MASYARAKAT INDONESI MEMBUTUHKAN KARYAWAN/KARYAWTI DENGAN SYARAT SBB : 1. PRIA 2. WANITA LEBIH DIUTAMAKAN 3. PEDIDIKAN MIN SLTA / SEDERAJAT (SEMUA JURUSAN) 4. USIA MAKSIMAL 23 THN 5. SEHAT JASMANI DAN ROHANI 6. TINGGI BADAN PRIA 160 CM, WANITA 155 CM 7. TIDAK SEDANG MENDERITA SAKIT KULIT 8. TIDAK BUTA WARNA 9. TIDAK MEMILIKI KETERGANTUNGAN OBAT 10. BERAMBUT PENDEK DAN RAPI (BAGI PRIA) 11. TIDAK BERTATO DAN TIDAK BERTINDIK (BAGI PRIA) 12. TIDAK TERLIBAT DALAM TINDAK KRIMINAL ( DIBUKTIKAN DENGAN SKCK) 13. PENEMPATAN DI SURABAYA KIRIMKAN LAMARAN BERUPA CV, FOTO 4X6 BERWARNA, FOTOCOPY KTP, IJAZAH DAN TRANSKIP NILAI, SURAT DOKTER, KARTU KELUARGA DAN SKCK DARI KEPOLISIAN. LAMARAN DIKIRIM ATAU DATANG LANGSUNG KE JL. KALIRUNGKUT NO. 07-09 SURABAYA ATAU EMAIL jobs@jacobis.co.id NB. HANYA KANDIDAT YANG MEMENUHI PERSYARATAN YANG AKAN DIPANGGIL', 'low jacobis [1600x1200].jpg', '', '', ''),
(5564, 'BBPLKLN CEVEST', 'NURHAYATI', '25/02/2014', 'TES KEPRIBADIAN CALON KARYAWAN PT. GS. BATTERY', 'Tes Kepribadian Calon Karyawan PT. GS. Batttery di BBPLKLN Cevest Bekasi', 'spanduk(2).jpg', '', '', ''),
(5565, 'BBPLKLN CEVEST', 'NURHAYATI', '25/02/2014', 'TES KEPRIBADIAN CALON KARYAWAN PT. GS. BATTERY', 'Pihak perusahaan memberikan pengarahan kepada peserta tes kepribadian di Asrama Baru BBPLKLN', 'pengarahan 1(2).jpg', '', '', ''),
(5566, 'BBPLKLN CEVEST', 'NURHAYATI', '25/02/2014', 'TES KEPRIBADIAN CALON KARYAWAN PT. GS. BATTERY', 'Alumni pelatihan BBPLKLN mengikuti tes kepribadian Calon Karyawan PT. GS. Battery', 'simak 3.jpg', '', '', ''),
(5567, 'BBPLKLN CEVEST', 'NURHAYATI', '25/02/2014', 'TES KEPRIBADIAN CALON KARYAWAN PT. GS. BATTERY', 'Setelah lulus pada tahap pertama, 42 orang alumni pelatihan pencari kerja di BBPLKLN Cevest mengikuti tes kepribadian di PT. GS Battery', 'simak 2.jpg', '', '', ''),
(5568, 'UPTPK SUMENEP', 'Rina Fitri S', '26/02/2014', 'PEMBUKAAN PELATIHAN MTU (APBD) TAHUN ANGGARAN 2014 KEJURUAN MENJAHIT DI DESA KARANGPENANG ONJUR KEC. KARANGPENANG KAB. SAMPANG', 'ACARA PEMBUKAAN PELATIHAN (MTU) KEJURUAN MENJAHIT DI DESA KARANGPENANG ONJUR KEC. KARANGPENANG KAB SAMPANG YANG DIHADIRI OLEH BAPAK KEPALA UPT. PELATIHAN KERJA SUMENEP BESERTA STAF, BAPAK SEKCAM KEC. KARANGPENANG, BAPAK INSTRUKTUR KEJURUAN MENJAHIT SERTA 16 ORANG PESERTA PELATIHAN', 'dscn0239 (copy).jpg', '', '', ''),
(5569, 'UPTPK SUMENEP', 'Rina Fitri S', '26/02/2014', 'PEMBUKAAN PELATIHAN MTU (APBD) TAHUN ANGGARAN 2014 KEJURUAN BORDIR DI DESA MOKTESARE KEC. KADUNDUNG KAB. SAMPANG', 'ACARA PEMBUKAAN PELATIHAN (MTU) KEJURUAN BORDIR DI DESA MOKTESARE KEC. KADUNGDUNG KAB. SAMPANG YANG DIHADIRI OLEH BAPAK KEPALA UPT. PELATIHAN KERJA SUMENEP BESERTA STAF, BAPAK SEKCAM KEC. KADUNGDUNG, BAPAK INSTRUKTUR KEJURUAN BORDIR SERTA 16 ORANG PESERTA PELATIHAN KEJURUAN BORDIR', 'dscn0247 (copy).jpg', '', '', ''),
(5570, 'BBPLKDN BANDUNG', 'yusnita karolina', '26/02/2014', 'Program Pelatihan Berbasis Kompetensi 2014', 'BBPLKDN Bandung membuka Program Pelatihan Berbasis Kompetensi (PBK) yang pendaftarannya di mulai dari bulan februari 2014', 'flyer2ok3(1).jpg', '', '', ''),
(5571, 'BBPLKLN CEVEST', 'NURHAYATI', '26/02/2014', 'SELEKSI KERJA PT. DHARMA POLIPLAST', 'PENGARAHAN', 'pengarahan 5.jpg', '', '', ''),
(5572, 'BBPLKLN CEVEST', 'NURHAYATI', '26/02/2014', 'SELEKSI KERJA PT. DHARMA POLIPLAST', 'SELEKSI KERJA PT. DHRAMA POLIPLAST', 'spanduk 2.jpg', '', '', ''),
(5573, 'BBPLKLN CEVEST', 'NURHAYATI', '26/02/2014', 'SELEKSI KERJA PT. DHARMA POLIPLAST', 'PESERTA TES SELEKSI', 'simak 4.jpg', '', '', ''),
(5574, 'BBPLKLN CEVEST', 'NURHAYATI', '26/02/2014', 'SELEKSI KERJA PT. DHARMA POLIPLAST', 'PENGARAHAN', 'pengarahan 6.jpg', '', '', ''),
(5575, 'UPTPK KEDIRI', 'RIZA WARDHA', '27/02/2014', 'PENDAFTARAN SISWA BARU TA 2014 PELATIHAN PROGRAM REGULER (GRATIS) UPT PELATIHAN KERJA KEDIRI', 'Telah dibuka Pendaftaran Siswa Baru TA 2014 untuk Program Reguler (Gratis/ Tanpa dipungut biaya) UPT Pelatihan Kerja Kediri.', 'tn_img001.jpg', '', '', ''),
(5576, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'Pelaksanaan tes', 'spanduk 1.jpg', '', '', ''),
(5577, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'pelaksanaan tes', 'dari belakang 1.jpg', '', '', ''),
(5578, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'pelaksanaan tes', 'dari samping jelas.jpg', '', '', ''),
(5579, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'pelaksanaan tes', 'dari belakang full.jpg', '', '', ''),
(5580, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'pelaksanaan tes', 'pembimbing.jpg', '', '', ''),
(5581, 'BBPLKLN CEVEST', 'NURHAYATI', '04/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. PAKOAKUINA DI BBPLKLN CEVEST', 'pelaksanaan tes', 'dari samping(2).jpg', '', '', ''),
(5582, 'BLKI BANGKA BELITUNG', 'Riduan', '04/03/2014', 'ACARA PEMBUKAAN PELATIHAN DI BLKI TAHUN 2014', 'TANGGAL 17 PEBRUARI 2014 ACARA PEMBUKAAN PELATIHAN YANG DI BUKA LANGSUNG OLEH GUBERNUR KEPULAUAN BANGKA BELITUNG RUSTAM EFFENDI DI UPTD. BLKI BABEL', 'blk3.jpg', '', '', ''),
(5583, 'BLKI BANGKA BELITUNG', 'Riduan', '04/03/2014', 'PENINJAUAN WORKSHOP OTOMOTIF 17 PEB 2014', 'PENINJAUAN WORKSHOP OTOMOTIF DI BLKI OLEH KEPALA DINAS TENAGA KERJA DAN TRANSMIGRASI SUGIANTO', 'w.o.jpg', '', '', ''),
(5584, 'BLKI BANGKA BELITUNG', 'Riduan', '04/03/2014', 'PENINJAUAN WORKSHOP LISTRIK 17 PEB 2014', 'KEPALA DINAS TENAGA KERJA DAN TRANSMIGRASI BERSAMA KEPALA UPTD. BLKI', 'w.lis.jpg', '', '', ''),
(5585, 'BLKI BANGKA BELITUNG', 'Riduan', '04/03/2014', 'PENINJAUAN WORKSHOP LAS 17 PEB 2014', 'PENINJAUAN WORKSHOP LAS 17 PEB 2014 OLEH KEPALA DINAS TENAGA KERJA DAN TRANSMIGRASI BERSAMA KEPALA UPTD. BLKI', 'wlas.jpg', '', '', ''),
(5586, 'BLKI BANGKA BELITUNG', 'Riduan', '08/11/2014', 'GUBERNUR MEMBERI ARAHAN DAN PETUNJUK KEPADA PEJABAT DISNAKERTRANS BABEL', 'GUBERNUR MEMBERI ARAHAN DAN PETUNJUK KEPADA KEPALA DINAS TENAGA KERJA DAN TRANSMIGRASI, KEPALA UPTD BLKI DAN UNSUR INSTANSI LAINNYA SEBELUM PEMBUKAAN PELATIHAN DI BLKI 17 PEB 2014 DI RUANG KEPALA UPTD. BLKI BANGKA BELITUNG', 'mt.jpg', '', '', ''),
(5587, 'BLKI BANGKA BELITUNG', 'Riduan', '04/03/2014', 'IDENTIKASI LANGSUNG KEPERUSAHAAN', 'STAF KIOS 3 IN 1 MELAKSANAKAN IDENTIFIKASI KEBUTUHAN LATIHAN KERJA DI PERUSAHAAN DI BELITUNG DAN BELITUNG TIMUR UNTUK LEBIH MENGUPDATE DAN PENYESUAIAN KEBUTUHAN PELATIHAN OLEH DUNIA USAHA DAN INDUSTRI PADA TANGGAL 20 PEB 2014', 'ds.jpg', '', '', ''),
(5589, 'BLK SOLOK', 'Nola Zuhana', '05/03/2014', 'Pembukan pelatihan APBD di Nagari Kinari Kec. Bukit Sundi', 'dihadiri oleh Bapak Camat Bukit Sundi, Kepala BLK, dan Bapak Walinagari Kinari', 'dsc00878.jpg', '', '', ''),
(5590, 'BLK SOLOK', 'Nola Zuhana', '05/03/2014', 'Pembukaan Pelatihan Menjahit di Nagari Kinari Kec. Bukit Sundi', 'Calon Peserta sedang mendengarkan pengarahan dari Bapak Camat', 'dsc00880.jpg', '', '', ''),
(5591, 'BLK SOLOK', 'Nola Zuhana', '05/03/2014', 'Pembukaan Pelatihan Menjahit di Nagari Kinari Kec. Bukit Sundi', 'Siswa sedang mendengarkan pengarahan dari Bapak Wali Nagari Kinari', 'dsc00879.jpg', '', '', ''),
(5592, 'BLK SOLOK', 'Nola Zuhana', '05/03/2014', 'Pembukaan Pelatihan Menjahit di Nagari Kinari Kec. Bukit Sundi', 'Foto bersama dengan Pak Camat, Wali Nagari serta Instruktur menjahit Bapak Rizal Khairal, S.Pd', 'dsc00891.jpg', '', '', ''),
(5593, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'PEMBUKAAN PELATIHAN KEJURUAN MENJAHIT, BORDIR, DAN TEKNOLOGI INFORMATIKA', 'Pembukaan pelatihan menjahit, border, dan teknologi informatika diselenggarakan pada tanggal 03 Maret 2014, bertempat di BLK Kabupaten Pasuruan oleh Kepala Bidang Lattas Penta Disnakersostrans Kab. Pasuruan beserta Camat setempat, dan dihadiri oleh seluruh peserta pelatihan kejuruan.', 'dsc04132 [640x480].jpg', '', '', ''),
(5594, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'FASILITAS BAGI PENCARI KERJA', 'Fasilitas disediakan bagi pencari kerja yang ingin mengakses informasi lowongan kerja di Kios 3 in 1.', 'dsc04112 [640x480].jpg', '', '', ''),
(5595, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'SENAM KEBUGARAN JASMANI', 'Senam kebugaran jasmani diadakan sebelum para peserta pelatihan memulai kegiatannya.', 'dsc04170 [640x480].jpg', '', '', ''),
(5596, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'RUANG PELATIHAN KEJURUAN AUTOMOTIVE R4', 'Ruang pelatihan kejuruan automotive R4 dilengkapi dengan beberapa fasilitas dan peralatan bagi peserta pelatihan.', 'dsc04190 [640x480].jpg', '', '', ''),
(5597, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'KEGIATAN PELATIHAN KEJURUAN AUTOMOTIVE R2', 'Kegiatan pelatihan kejuruan automotive R2 diawali dengan pembekalan teori yang selanjutnya diikuti dengan praktek.', 'dsc04212 [640x480].jpg', '', '', ''),
(5598, 'BLK KAB. PASURUAN', 'Kiky', '07/03/2014', 'PERSIAPAN PERESMIAN GEDUNG BLK KABUPATEN PASURUAN', 'Peresmian Gedung BLK Pemerintah Kabupaten Pasuruan diselenggarakan pada hari ini Jum\'at, 07 Maret 2014 oleh Menteri Tenaga Kerja dan Transmigrasi Republik Indonesia yang bertempat di BLK Kabupaten Pasuruan Jln. Raya Rejoso Desa Sambirejo Kec. Rejoso', 'dsc04245 [800x600].jpg', '', '', ''),
(5599, 'UPTPK SUMENEP', 'Melly Herawati', '11/03/2014', 'SELEKSI CALON PESERTA PELATIHAN APBD INSTIT SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER', 'PADA TANGGAL 05 MARET 2014, DIADAKAN SELEKSI CALON PESERTA PELATIHAN SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER INSTIT APBD TAHUN ANGGARAN 2014. SELEKSI INI DIIKUTI OLEH 21 PESERTA DARI SUB KEJURUAN SEPEDA MOTOR DAN 52 PESERTA DARI SUB KEJURUAN OPERATOR KOMPUTER.', '20140305_092701 (copy).jpg', '', '', ''),
(5600, 'UPTPK SUMENEP', 'Melly Herawati', '11/03/2014', 'SELEKSI CALON PESERTA PELATIHAN APBD INSTIT SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER', 'PADA TANGGAL 05 MARET 2014, DIADAKAN SELEKSI CALON PESERTA PELATIHAN SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER INSTIT APBD TAHUN ANGGARAN 2014. SALAH SATU PANITIA MELAKUKAN SELEKSI WAWANCARA KEPADA CALON PESERTA PELATIHAN', '20140305_111429 (copy).jpg', '', '', ''),
(5601, 'UPTPK SUMENEP', 'Melly Herawati', '11/03/2014', 'SOSIALISASI PELATIHAN KE MAN SUMENEP', '06/03/2014, PETUGAS KIOS 3IN1++ BERSAMA KEPALA SEKSI PENGEMBANGAN DAN PEMASARAN BAPAK MOH YUSUF, S.Pd MELAKUKAN SOSIALISASI PELATIHAN KE SEKOLAH MAN SUMENEP.', '20140306_093335 (copy).jpg', '', '', '');
INSERT INTO `2011infokios` (`id`, `kios`, `admin`, `tglkirim`, `judulberita`, `deskripsi`, `photoberita`, `cad1`, `cad2`, `cad3`) VALUES
(5602, 'UPTPK SUMENEP', 'Melly Herawati', '11/03/2014', 'PEMBUKAAN PELATIHAN INSTIT APBD 2014 SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER A.1', 'TANGGAL 10 MARET 2014, DIADAKAN PEMBUKAAN PELATIHAN INSTIT APBD 2014 SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER A.1. PEMBUKAAN INI DIIKUTI OLEH PESERTA PELATIHAN, INSTRUKTUR, KEPALA SEKSI PP, KEPALA SEKSI PS, KEPALA UPT BESERTA PANITIA.', '20140310_094244 (copy).jpg', '', '', ''),
(5603, 'UPTPK SUMENEP', 'Melly Herawati', '11/03/2014', 'PEMBUKAAN PELATIHAN INSTIT APBD 2014 SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER A.1', 'TANGGAL 10 MARET 2014, DIADAKAN PEMBUKAAN PELATIHAN INSTIT APBD 2014 SUB KEJURUAN SEPEDA MOTOR DAN OPERATOR KOMPUTER A.1. PEMBUKAAN INI DIIKUTI OLEH PESERTA PELATIHAN, INSTRUKTUR, KEPALA SEKSI PP, KEPALA SEKSI PS, KEPALA UPT BESERTA PANITIA.', '20140310_094237 (copy).jpg', '', '', ''),
(5604, 'BLKI BANGKA BELITUNG', 'Riduan', '11/03/2014', 'PELATIHAN BANGUNAN SUB KEJURUAN GAMBAR BANGUNAN', 'SAAT SAAT PELATIHAN AUTOCAD DI RUANG IT BLKI 2014', '_dsc1038.jpg', '', '', ''),
(5605, 'BLKI BANGKA BELITUNG', 'Riduan', '11/03/2014', 'PELATIHAN LAS LISTRIK DI WORKSHOP BLKI BABEL', 'INSTRUKTUR SEDANG MEMBERIKAN ARAHAN KEPADA PESERTA PELATIHAN LAS', '_dsc1047.jpg', '', '', ''),
(5606, 'BLKI BANGKA BELITUNG', 'Riduan', '11/03/2014', 'PELATIHAN SEPEDA MOTOR DI WORKSHOP OTOMOTIF', 'INSTRUKTUR MEMBERIKAN KIAT-KIAT DALAM PERBAIKAN KENDARAAN BERMOTOR', '_dsc1042.jpg', '', '', ''),
(5607, 'BLKI BANGKA BELITUNG', 'Riduan', '11/03/2014', 'PELATIHAN INSTALASI LISTRIK DI WORKSHOP BLKI BABEL', 'INSTRUKTUR LISTRIK SEDANG MEMANTAU DAN MENGARAH PENGGUNAAN PLC DI WORKSHOP BLKI', '_dsc1050.jpg', '', '', ''),
(5608, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH', 'PT. MAYORA INDAH melaksanakan tes seleksi kerja di BBPLKLN Cevest Bekasi pada hari Selasa, 11 Maret 2014 . Tes seleksi ini bekerjasama dengan BKK SMK YPIA Cakung.', 'spanduk(3).jpg', '', '', ''),
(5609, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'Pelaksanaan tes seleksi', 'pengarahan(11).jpg', '', '', ''),
(5610, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'peserta tes', 'peserta(2).jpg', '', '', ''),
(5611, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'pengukuran tinggi peserta tes', 'ukur tinggi 1.jpg', '', '', ''),
(5612, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'pengukuran tinggi peserta', 'ukur tinggi 2.jpg', '', '', ''),
(5613, 'BBPLKLN CEVEST', 'NURHAYATI', '11/03/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'pengukuran tinggi peserta', 'antri.jpg', '', '', ''),
(5614, 'BLKI PADANG', 'sugianto', '11/03/2014', 'Rekruit Calon Tenaga Kerja', 'Foto: Direktur PT Muaro Prima Utama Perusahaan di Batam yang bergerak dibidang Pabrikasi dan Manufacturing berniat untuk merekruit Peserta Pelatihan jurusan las BLKI Padang untuk bekerja di Perusahaannya di Batam', 'foto rekruit calon tkkkk(2).jpg', '', '', ''),
(5615, 'BLKI BANGKA BELITUNG', 'Riduan', '12/03/2014', 'PENDAFTARAN PELATIHAN BLKI BABEL SISTEM ONLINE', 'SEGERA DAFTAR DIRI ANDA BUJANG DAYANG BANGKA BELITUNG DALAM PELATIHAN DI BLKI BANGKA BELITUNG TAHUN 2014 UNTUK INFO HUB. 0717 421050 DAN HP, 081995369206 (RIDUAN) STAF KIOS 3IN1 GRATIS DAN DAPAT SKILLNYA UNTUK KEJURUAN LIHAT DIBERITA INFO DIBLKI KIOS 3IN1.NET PELUANG PENEMPATAN DI BIDANG PERHOTELAN DI BANGKA BELITUNG ANDA DILATIH SIAP DI TEMPAT DI HOTEL DIBANGKA BELITUNG DGN SYARAT DAN KETENTUAN BERLAKU. AYOO BURUAN TEMPAT TERBATAS.......!!!!!!!!!!!!!!!!!!!!!!', 'brosur blki.jpg', '', '', ''),
(5617, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG', 'PEMBUKAAN PELATIHAN SWADANA PSG 1. SMK DH PEPABRI MAKASSAR 2. SMK RAHMANI BETELEME, MOROWALI, SULTENG 3. SMK SIKAMALI TORAJA 4. SMK NEG 1 PATALLASSANG, GOWA 5. SMK NEG. 1 TOBADAK MAMUJU, SULBAR 6. SMK NEG 1 TOILI, SULTENG', 'dsc07368.jpg', '', '', ''),
(5618, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG', 'PEMBUKAAN PELATIHAN SWADANA PSG 1. SMK DH PEPABRI MAKASSAR 2. SMK RAHMANI BETELEME, MOROWALI, SULTENG 3. SMK SIKAMALI TORAJA 4. SMK NEG 1 PATALLASSANG, GOWA 5. SMK NEG. 1 TOBADAK MAMUJU, SULBAR 6. SMK NEG 1 TOILI, SULTENG Penyematan Tanda Peserta Pelatihan oleh Kepala sekolah SMK DH PEPABRI Makassar Bapak, Alimuddin S.Pd.', 'dsc07389.jpg', '', '', ''),
(5619, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG', 'PEMBUKAAN PELATIHAN SWADANA PSG 1. SMK DH PEPABRI MAKASSAR 2. SMK RAHMANI BETELEME, MOROWALI, SULTENG 3. SMK SIKAMALI TORAJA 4. SMK NEG 1 PATALLASSANG, GOWA 5. SMK NEG. 1 TOBADAK MAMUJU, SULBAR 6. SMK NEG 1 TOILI, SULTENG', 'dsc07377.jpg', '', '', ''),
(5620, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG', 'PEMBUKAAN PELATIHAN SWADANA PSG 1. SMK DH PEPABRI MAKASSAR, Kejuruan Mobil Bensin dan Instalasi Penerangan 2. SMK RAHMANI BETELEME, MOROWALI, SULTENG, Kejuruan Mobil Bensin 3. SMK SIKAMALI TORAJA, Kejuruan Mobil Bensin 4. SMK NEG 1 PATALLASSANG, GOWA, Kejuruan Teknik Komputer dan Jaringan 5. SMK NEG. 1 TOBADAK MAMUJU, SULBAR, Kejuruan Mobil Bensin 6. SMK NEG 1 TOILI, SULTENG, Kejuruan Sepeda Motor, Audio Video, dan TKJ Penyematan Tanda Peserta Pelatihan oleh Kepala BLKI Makassar Bapak, H. Muhammad Akbar, SH. MH.', 'dsc07388(1).jpg', '', '', ''),
(5621, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '12/03/2014', 'PENANDATANGANAN PRASASTI', 'Pengukuhan tanda tangan oleh Menteri Tenaga Kerja dan Transmigrasi Republik Indonesia.', 'dsc04323 [640x480].jpg', '', '', ''),
(5622, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '12/03/2014', 'PEMOTONGAN BALON BERHADIAH', 'Balon berhadiah dari Disnakersostrans bekerja sama dengan Radar Bromo.', 'img_8495 [640x480].jpg', '', '', ''),
(5623, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '12/03/2014', 'PEMOTONGAN PITA', 'Pemotongan pita pada acara peresmian gedung Balai Latihan Kerja (BLK) Kab. Pasuruan yang dilaksanakan pada hari Jumat tanggal 7 Maret 2014 oleh Menteri Tenaga Kerja dan Transmigrasi Republik Indonesia Bpk. Drs. H. A. Muhaimin Iskandar, MSi.', 'img_8526 [640x480].jpg', '', '', ''),
(5624, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '12/03/2014', 'PENINJAUAN DENAH LOKASI', 'Denah lokasi Balai Latihan Kerja (BLK) Kab. Pasuruan dari skala 1:300', 'img_8566 [640x480].jpg', '', '', ''),
(5625, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PENDAFTARAN PELATIHAN REGULER 2014', 'SUASANA PENDAFTARAN PELATIHAN REGULER DI KIOS 3IN1 MAKASSAR YANG DIBUKA MULAI 10 MARET 2014', 'dsc07394.jpg', '', '', ''),
(5626, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PENDAFTARAN PELATIHAN REGULER 2014', 'SUASANA PENDAFTARAN PELATIHAN REGULER DI KIOS 3IN1 MAKASSAR YANG DIBUKA MULAI 10 MARET 2014', 'dsc07395.jpg', '', '', ''),
(5627, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PENDAFTARAN PELATIHAN REGULER 2014', 'SUASANA PENDAFTARAN PELATIHAN REGULER DI KIOS 3IN1 MAKASSAR YANG DIBUKA MULAI 10 MARET 2014', 'dsc07402.jpg', '', '', ''),
(5628, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PENDAFTARAN PELATIHAN REGULER 2014', 'SUASANA PENDAFTARAN PELATIHAN REGULER DI KIOS 3IN1 MAKASSAR YANG DIBUKA MULAI 10 MARET 2014', 'dsc07396.jpg', '', '', ''),
(5629, 'BLKI MAKASSAR', 'irmiani', '12/03/2014', 'PENDAFTARAN PELATIHAN REGULER 2014', 'SUASANA PENDAFTARAN PELATIHAN REGULER DI KIOS 3IN1 MAKASSAR YANG DIBUKA MULAI 10 MARET 2014', 'dsc07397.jpg', '', '', ''),
(5630, 'BLK KAB. PASURUAN', 'Yudha Adhi Pratama', '12/03/2014', 'PERCOBAAN APLIKASI KIOS3IN1', 'Aplikasi Kios3in1 di coba langsung oleh Menteri Tenaga Kerja dan Transmigrasi Republik Indonesia.', 'img_8573 [640x480].jpg', '', '', ''),
(5631, 'UPTPK SITUBONDO', 'nitha', '14/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Menjahit di PP. Nurul Hikam Desa Kesambirampak Kec. Kapongan', 'Pembukaan Pelatihan MTU kejuruan menjahit yang dilaksanakan pada tanggal 11 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Nurul hikam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8023.jpg', '', '', ''),
(5632, 'UPTPK SITUBONDO', 'nitha', '14/03/2014', 'Pembukaan Pelatihan Berbasis masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga kerja(PKPTK) Kejuruan Menjahit di PP. Nurul hikam Desa Kesambirampak Kec. Kapongan', 'Pembukaan Pelatihan MTU kejuruan menjahit yang dilaksanakan pada tanggal 11 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Nurul hikam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8031.jpg', '', '', ''),
(5633, 'UPTPK SITUBONDO', 'nitha', '14/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga kerja (PKPTK) Kejuruan Menjahit di PP. Nurul hikam Desa Kesambirampak Kec. Kapongan', 'Pembukaan Pelatihan MTU kejuruan menjahit yang dilaksanakan pada tanggal 11 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Nurul hikam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8039.jpg', '', '', ''),
(5634, 'UPTPK SITUBONDO', 'nitha', '14/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga kerja (PKPTK) Kejuruan Menjahit di PP. Nurul hikam Desa Kesambirampak Kec. Kapongan', 'Pembukaan Pelatihan MTU kejuruan menjahit yang dilaksanakan pada tanggal 11 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Nurul hikam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8018.jpg', '', '', ''),
(5635, 'BLK KULONPROGO', 'nur qodariyanto', '14/03/2014', 'PROSES SELEKSI PT KATSUSHIRO INDONESIA', 'Seleksi dilaksanakan pada hari Rabu, 12 Maret 2014 di UPTD BLK Kulon Progo, diikuti 34 peserta', 'p1020733.jpg', '', '', ''),
(8045, 'UPTPK SINGOSARI', 'eva charisma', '04/01/2016', 'Agenda Pertemuan Instruktur UPT Pelatihan Kerja Singosari', 'Singosari, 30 Desember 2015. Agenda Pertemuan INstruktur UPT Pelatihan Kerja Singosari dihadiri oleh Kepala UPT Pelatihan Kerja Singosari (Drs. Hariyadi Budihardjo, M. Pd) dilanjutkan dengan diseminasi.', 'agenda pertemuan instruktur.jpg', '', '', ''),
(5637, 'BLK SOLOK', 'Nola Zuhana', '18/03/2014', 'Siswa sedang Praktek', 'Pelatihan Menjahit di Nagari Kinari Kec. Bukit Sundi', 'dsc00987.jpg', '', '', ''),
(5638, 'BLK SOLOK', 'Nola Zuhana', '18/03/2014', 'Siswa sedang Praktek', 'Pelatihan Menjahit di Nagari Kinari Kec. Bukit Sundi', 'dsc00995.jpg', '', '', ''),
(5639, 'BLK SOLOK', 'Nola Zuhana', '18/03/2014', 'Siswa sedang Praktek', 'Foto dengan Kepala UPT BLK yang sedang berkunjung ke Lokasi Pelatihan Menjahit', 'dsc01008.jpg', '', '', ''),
(5640, 'UPTPK JOMBANG', 'IFA', '19/03/2014', 'JOB FAIR 2014 - UPT PELATIHAN KERJA JOMBANG', 'HADIRILAH JOB FAIR 2014 YANG DIADAKAN OLEH UPT PELATIHAN KERJA JOMBANG YANG AKAN DIIKUTI OLEH KURANG LEBIH 50 PERUSAHAAN BAIK DARI JOMBANG MAUPUN LUAR JOMBANG. ACARA TERSEBUT AKAN DILAKSANAKAN DI HALAMAN KANTOR UPT PELATIHAN KERJA JOMBANG PADA TANGGAL 26 MARET 2014 PUKUL 08.00 WIB. JANGAN SAMPAI DILEWATKAN KESEMPATAN UNTUK MENDAPATKAN PEKERJAAN !!!! GRATIIIIIISSSSS......', 'leaflet - new [1280x768].jpg', '', '', ''),
(5641, 'BLKI BANGKA BELITUNG', 'Riduan', '19/03/2014', 'SEGERA DAFTARKAN DIRI ANDA DIPELATIHAN SESUAI KEINGINAN ANDA !!!', 'DENGAN PELATIHAN KEJURUAN SBB: 1. KEJURUAN BANGUNAN - SUB KEJURUAN GAMBAR BANNGUNAN - SUB KEJURUAN FURNITURE 2. KEJURUAN GARMEN APAREL - SUB KEJURUAN MENJAHIT 3. KEJURUAN PARIWISATA - SUB KEJURUAN BAHASA KOREA - SUB KEJURUAN PERHOTELAN 4. KEJURUAN PERIKANAN - SUB KEJURUAN BUDIDAYA 5. KEJURUAN PROSESSING - SUB KEJURUAN TATA BOGA 6. KEJURUAN REFRIGERATION - SUB KEJURUAN AC RUANGAN 7. KEJURUAN TATA KECANTIKAN - SUB KEJURUAN TATA RIAS PENGANTIN 8. KEJURUAAN TEKNIK LAS - SUB KEJURUAN FABRIKASI - SUB KEJURUAN LAS INDUSTRI- LISTRIK 9. KEJURUAN TEKNIK LISTRIK - SUB KEJURUAN INSTALASI PENERANGAN 10. KEJURUAN OTOMOTIF - SUB KEJURUAN ALAT BERAT - SUB KEJURUAN KENDARAAN RINGAN- BENSIN - SUB KEJURUAN SEPEDA MOTOR 11. TEKNOLOGI INFORMASI DAN KOMUNIKASI - SUB KEJURUAN GRAPHIC DESIGN - SUB KEJURUAN IT GOVERNANCE - SUB KEJURUAN OPERATOR KOMPUTER KETIK WEB . WWW.KIOS3IN1.NET PILIH BLKI BANGKA BELITUNG KLIK MENU PELATIHAN LANGSUNG ANDA DAFTAR SESUAI MINAT ANDA......? SEMUA GRATIS * TEMPAT TERBATAS .......................................... INFO HUB 0717 421050 BLKI BABEL ATAU HP. 081995369206 (RIDUAN) STAF KIOS 3 IN1', 'brosur blki (500 x 363).jpg', '', '', ''),
(5642, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) APBD 2014 Kejuruan Salon/Tata rias di PP. Assalam Desa Sumberanyar Kec. Banyuputih', 'Pembukaan Pelatihan MTU kejuruan salon/tata rias yang dilaksanakan pada tanggal 18 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Assalam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8233.jpg', '', '', ''),
(5643, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Salon/Tata rias di PP. Assalam Desa Sumberanyar Kec. Banyuputih', 'Pembukaan Pelatihan MTU kejuruan salon/tata rias yang dilaksanakan pada tanggal 18 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Assalam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8236.jpg', '', '', ''),
(5644, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Salon/Tata rias di PP. Assalam Desa Sumberanyar Kec. Banyuputih', 'Pembukaan Pelatihan MTU kejuruan salon/tata rias yang dilaksanakan pada tanggal 18 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Assalam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8243.jpg', '', '', ''),
(5645, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Salon/Tata rias di PP. Assalam Desa Sumberanyar Kec. Banyuputih', 'Pembukaan Pelatihan MTU kejuruan salon/tata rias yang dilaksanakan pada tanggal 18 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengurus PP. Assalam yg juga menyampaikan rasa terima kasih. Kepala UPT Pelatihan kerja situbondo juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'img_8248.jpg', '', '', ''),
(5646, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Instalasi penerrangan di PP. Ibnu Kholdun Al Hasyimi Desa Widoropayung Kec. Besuki', 'Pembukaan Pelatihan MTU kejuruan Instalasi penerangan yang dilaksanakan pada tanggal 19 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengasuh PP. Ibnu kholdun al hasyimi yg juga menyampaikan ucapan terima kasih, serta perwakilan dari Desa Widoropayung. Kepala UPT Pelatihan kerja situbondo atau yang dalam hal ini diwakil oleh Kasi Pengembangan dan Pemasaran juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'p3190010.jpg', '', '', ''),
(5647, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja (PKPTK) Kejuruan Instalasi penerangan di PP. Ibnu Kholdun AL Hasyimi Desa Widoropayung Kec. Besuki', 'Pembukaan Pelatihan MTU kejuruan Instalasi penerangan yang dilaksanakan pada tanggal 19 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengasuh PP. Ibnu kholdun al hasyimi yg juga menyampaikan ucapan terima kasih, serta perwakilan dari Desa Widoropayung. Kepala UPT Pelatihan kerja situbondo atau yang dalam hal ini diwakil oleh Kasi Pengembangan dan Pemasaran juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'p3190016.jpg', '', '', ''),
(5648, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Instalasi Penerangan di PP. Ibnu Kholdun Al Hasyimi Desa Widoropayung Kec. Besuki', 'Pembukaan Pelatihan MTU kejuruan Instalasi penerangan yang dilaksanakan pada tanggal 19 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengasuh PP. Ibnu kholdun al hasyimi yg juga menyampaikan ucapan terima kasih, serta perwakilan dari Desa Widoropayung. Kepala UPT Pelatihan kerja situbondo atau yang dalam hal ini diwakil oleh Kasi Pengembangan dan Pemasaran juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'p3190017.jpg', '', '', ''),
(5649, 'UPTPK SITUBONDO', 'nitha', '20/03/2014', 'Pembukaan Pelatihan Berbasis Masyarakat Program Peningkatan Kualitas dan Produktivitas Tenaga Kerja(PKPTK) Kejuruan Instalasi penerangan di PP. Ibnu Kholdun Al Hasyimi Desa Widoropayung Kec. Besuki', 'Pembukaan Pelatihan MTU kejuruan Instalasi penerangan yang dilaksanakan pada tanggal 19 maret 2014 berlangsung lancar. pada kesempatan ini di hadiri oleh Pengasuh PP. Ibnu kholdun al hasyimi yg juga menyampaikan ucapan terima kasih, serta perwakilan dari Desa Widoropayung. Kepala UPT Pelatihan kerja situbondo atau yang dalam hal ini diwakil oleh Kasi Pengembangan dan Pemasaran juga berkenan membuka secara resmi pelatihan tersebut. pelatihan ini dilaksanakan kurang lebih selama 1 bulan, peserta mendapat makan siang dan bantuan uang transport serta sertifikat bagi yang dinyatakan lulus.', 'p3190021.jpg', '', '', ''),
(5650, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '25/03/2014', 'kEGIATAN PELATIHAN KEJURUAN TEKNIK LISTRIK', 'Acara pembukaan kegiatan pelatihan PSG kejuruan Teknik Listrik. Diikuti sebanyak 22 siswa dari sekolah SMK Sukodadi Lamongan.', 'img_8891 (copy).jpg', '', '', ''),
(5651, 'UPTPK TUBAN', 'Gracia Lorna Cinantya', '25/03/2014', 'KEGIATAN PELATIHAN KEJURUAN TEKNIK LISTRIK', 'Adapun 22 peserta adalah siswa yang masih duduk di bangku kelas XI. Pembukaan acara diberikan pengarahan oleh Kepala Seksi Pelatihan dan Sertifikasi didampingi Instruktur Kejuruan. Pengarahan yang diberikan adalah seputar pelatihan serta persyaratan yang harus dikumpulkan selama mengikuti pelatihan.', 'img_8893 (copy).jpg', '', '', ''),
(5653, 'UPTPK KEDIRI', 'RIZA WARDHA', '25/03/2014', 'KUNJUNGAN KE SMK CANDA BHIRAWA, PARE', '(dari Pihak SMK Canda Bhirawa, Pare memberikan pengantar) Sosialisasi Program Pelatihan TA 2014 terhadap siswa-siswi kelas XII SMK Canda Bhirawa di Pare pada tanggal 25 Maret 2014 pukul 09.00 WIB s/d selesai.', 'tn_img_20140325_090850.jpg', '', '', ''),
(5654, 'UPTPK KEDIRI', 'RIZA WARDHA', '25/03/2014', 'KUNJUNGAN KE SMK CANDA BHIRAWA, PARE', 'Sosialisasi Program Pelatihan TA 2014 terhadap siswa-siswi kelas XII SMK Canda Bhirawa di Pare pada tanggal 25 Maret 2014 pukul 09.00 WIB s/d selesai bertempat di aula SMK Canda Bhirawa.', 'tn_img_20140325_090752.jpg', '', '', ''),
(5655, 'UPTPK KEDIRI', 'RIZA WARDHA', '25/03/2014', 'KUNJUNGAN KE SMK CANDA BHIRAWA, PARE', 'Sosialisasi Program Pelatihan TA 2014 terhadap siswa-siswi kelas XII SMK Canda Bhirawa di Pare pada tanggal 25 Maret 2014 pukul 09.00 WIB s/d selesai bertempat di aula SMK Canda Bhirawa.', 'tn_img_20140325_090900.jpg', '', '', ''),
(5656, 'UPTPK KEDIRI', 'RIZA WARDHA', '25/03/2014', 'KUNJUNGAN KE SMK CANDA BHIRAWA, PARE', '(dari Pihak SMK Canda Bhirawa, Pare memberikan pengantar) Sosialisasi Program Pelatihan TA 2014 terhadap siswa-siswi kelas XII SMK Canda Bhirawa di Pare pada tanggal 25 Maret 2014 pukul 09.00 WIB s/d selesai bertempat di aula SMK Canda Bhirawa.', 'tn_img_20140325_090824(1).jpg', '', '', ''),
(5657, 'UPTPK TUBAN', 'Amalia puji prasetia ningrum', '26/03/2014', 'KEGIATAN PELATIHAN KEJURUAN TEKNIK LISTRIK', '-', 'img_8899 (copy).jpg', '', '', ''),
(5658, 'BLKI PAPUA', 'Andri Gunawan', '26/03/2014', 'PESERTA PELATIHAN MOTOR TEMPEL DIHARAPKAN DAPAT TINGKATKAN KESEJAHTERAAN', 'Kepala BLKI Prov. Papua, Djoni Naa, SE.MS.i (tengah), Kepala Seksi Pelatihan dan Pemagangan BLKI Prov. Papua, Mince Yarangga,SE (kiri) dan Ketua TPKK Demta (kanan).', 'dscn0218.jpg', '', '', ''),
(5659, 'BLKI PAPUA', 'Andri Gunawan', '26/03/2014', 'PESERTA PELATIHAN MOTOR TEMPEL DIHARAPKAN DAPAT TINGKATKAN KESEJAHTERAAN', 'Peserta Pelatihan Motor Tempel Distrik Demta', 'dscn0222.jpg', '', '', ''),
(5660, 'BLKI PAPUA', 'Andri Gunawan', '26/03/2014', 'PESERTA PELATIHAN MOTOR TEMPEL DIHARAPKAN DAPAT TINGKATKAN KESEJAHTERAAN', 'Kepala BLKI Prov. Papua Saat Pukul Tifa Tanda Pelatihan Motor Tempel Bagi Pemuda Potensial Distrik Demta Secara Resmi Ditutup.', 'dscn0226.jpg', '', '', ''),
(5661, 'BLKI PAPUA', 'Andri Gunawan', '26/03/2014', 'PESERTA PELATIHAN MOTOR TEMPEL DIHARAPKAN DAPAT TINGKATKAN KESEJAHTERAAN', 'Kepala BLKI Prov. Papua didampingi Kepala Seksi dan PNS beserta Peserta Pelatihan Motor Tempel saat sesi foto bersama.', 'dscn0231.jpg', '', '', ''),
(5662, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'GEDUNG TUK BLK BOYOLALI', '-', 'edit 2 a2.jpg', '', '', ''),
(5663, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'GEDUNG TEMPAT UJI KOMPETENSI UPTD BLK BOYOLALI', '-', 'dsc00157 a1.jpg', '', '', ''),
(5664, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'APEL PAGI PEGAWAI', 'KEGIATAN APEL PAGI PEGAWAI DI LAKSANAKAN SETIAP HARI KERJA', 'apel pagi pegawai.jpg', '', '', ''),
(5668, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'APEL PAGI PESERTA', 'APEL PAGI PESERTA PELATIHAN DI LAKSANAKAN SETIAP PAGI SEBELUM PELAKSAAN KEGIATAN PEMBELAJARAN', 'apel pagi siswa 2.jpg', '', '', ''),
(5670, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'Kegiatan Apel Pagi Siswa', 'Kegiatan aple pagi peserta pelatihan yang di lanjutkan dengan Senam', '', '', '', ''),
(5671, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'APEL PAGI PESERTA PELATIHAN', 'Pelaksanaan Apel Pagi para peserta pelatihan yang di lanjutkan dengan Senam Pagi', 'apel siswa b2.jpg', '', '', ''),
(5674, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'PELATIHAN KENDARAAN RINGAN MOBIL', '-', '', '', '', ''),
(5676, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'OTOMOPTIVE', 'PELATIHAN KENDARAAN RINGAN MOIBL', '', '', '', ''),
(5677, 'BLK BOYOLALI', 'Hartono', '27/03/2014', 'OTOMOPTIVE', 'PELATIHAN KENDARAAN RINGAN MOIBL', '', '', '', ''),
(5678, 'UPTPK NGANJUK', 'pramitasari', '01/04/2014', 'FOTO SELEKSI KEJURUAN PROCESSING', 'DALAM PELAKSANAAN PEREKRUTAN SISWA DIADAKAN BEBERAPA TAHAP SELEKSI , DIANTARANYA TAHAP SELEKSI WAWANCARA . PADA TAHAP SELEKSI INI BERTUJUAN UNTUK MENGGALI MINAT DAN BAKAT DARI PESERTA PELATIHAN , AGAR DALAM MENGIKUTI PELATIHAN MEREKA LEBIH SEMANGAT DAN TEKUN KARENA SESUAI BAKAT DAN MINAT MEREKA MASING - MASING', 'dsc00947(1).jpg', '', '', ''),
(5679, 'UPTPK NGANJUK', 'pramitasari', '01/04/2014', 'FOTO SELEKSI WAWANCARA KEJURUAN RIAS RAMBUT', 'DALAM PELAKSANAAN PEREKRUTAN SISWA DIADAKAN BEBERAPA TAHAP SELEKSI , DIANTARANYA TAHAP SELEKSI WAWANCARA . PADA TAHAP SELEKSI INI BERTUJUAN UNTUK MENGGALI MINAT DAN BAKAT DARI PESERTA PELATIHAN , AGAR DALAM MENGIKUTI PELATIHAN MEREKA LEBIH SEMANGAT DAN TEKUN KARENA SESUAI BAKAT DAN MINAT MEREKA MASING - MASING', '', '', '', ''),
(5680, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2248.jpg', '', '', ''),
(5681, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2255.jpg', '', '', ''),
(5682, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2266.jpg', '', '', ''),
(5683, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2276.jpg', '', '', ''),
(5684, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2278.jpg', '', '', ''),
(5685, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI DENGAN ANTARA BLKI MAKASSAR DENGAN PTPN X (persero) KEJURUAN PLC UNTUK PABRIK GULA TAKALAR, PABRIK GULA CAMMING DAN PABRIK GULA BONE, 12 MARET 2014', 'dscn2284.jpg', '', '', ''),
(5686, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI 1. SMK TAGARI, JURUSAN OTOMOTIF DAN GAMBAR RENCANA 2. SMK RINDING ALLO, JURUSAN OTOMOTIF DAN TEKNIK KOMPUTER & JARINGAN 3. SMK MATA ALLO, JURUSAN TEKNIK KOMPUTER & JARINGAN 4. SMK NEG 1 KESU\', JURUSAN OTOMOTIF 5. PT. MARUKI INTERNASIONAL INDONESIA, JURUSAN GAMBAR RENCANA', 'dscn2314.jpg', '', '', ''),
(5687, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI 1. SMK TAGARI, JURUSAN OTOMOTIF DAN GAMBAR RENCANA 2. SMK RINDING ALLO, JURUSAN OTOMOTIF DAN TEKNIK KOMPUTER & JARINGAN 3. SMK MATA ALLO, JURUSAN TEKNIK KOMPUTER & JARINGAN 4. SMK NEG 1 KESU\', JURUSAN OTOMOTIF 5. PT. MARUKI INTERNASIONAL INDONESIA, JURUSAN GAMBAR RENCANA', 'dscn2310.jpg', '', '', ''),
(5688, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI', 'PEMBUKAAN PELATIHAN SWADANA PSG DAN KERJASAMA INDUSTRI 1. SMK TAGARI, JURUSAN OTOMOTIF DAN GAMBAR RENCANA 2. SMK RINDING ALLO, JURUSAN OTOMOTIF DAN TEKNIK KOMPUTER & JARINGAN 3. SMK MATA ALLO, JURUSAN TEKNIK KOMPUTER & JARINGAN 4. SMK NEG 1 KESU\', JURUSAN OTOMOTIF 5. PT. MARUKI INTERNASIONAL INDONESIA, JURUSAN GAMBAR RENCANA', 'dscn2306.jpg', '', '', ''),
(5689, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN TRAINING WELDER DALAM RANGKA PEMBANGUNAN COMBAT BOOT 18 M ALUMINIUM KERJASAMA FASHARKAN MAKASSAR DENGAN BLKI MAKASSAR MAKASSAR. 17 MARET 2014', 'dscn2324.jpg', '', '', ''),
(5690, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN TRAINING WELDER DALAM RANGKA PEMBANGUNAN COMBAT BOOT 18 M ALUMINIUM KERJASAMA FASHARKAN MAKASSAR DENGAN BLKI MAKASSAR MAKASSAR. 17 MARET 2014', 'dscn2331.jpg', '', '', ''),
(5691, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN TRAINING WELDER DALAM RANGKA PEMBANGUNAN COMBAT BOOT 18 M ALUMINIUM KERJASAMA FASHARKAN MAKASSAR DENGAN BLKI MAKASSAR MAKASSAR. 17 MARET 2014', 'dscn2334.jpg', '', '', ''),
(5692, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'PEMBUKAAN PELATIHAN SWADANA KERJASAMA INDUSTRI', 'PEMBUKAAN TRAINING WELDER DALAM RANGKA PEMBANGUNAN COMBAT BOOT 18 M ALUMINIUM KERJASAMA FASHARKAN MAKASSAR DENGAN BLKI MAKASSAR MAKASSAR. 17 MARET 2014', 'dscn2337(1).jpg', '', '', ''),
(5693, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'PENGARAHAN KEPADA PESERTA TES PBK OLEH KEPALA SESKI PENYELENGGARA PELATIHAN', 'dsc07415.jpg', '', '', ''),
(5694, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'PENGARAHAN SEBELUM MEMULAI TES', 'dsc07418.jpg', '', '', ''),
(5695, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 PENGARAHAN OLEH KEPALA SEKSI PENYELENGGARA PELATIHAN', 'dsc07423.jpg', '', '', ''),
(5696, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 SUASANA TES TERTULIS', 'dsc07432.jpg', '', '', ''),
(5697, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 SUASANA TES TERTULIS', 'dsc07435.jpg', '', '', ''),
(5698, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 TES TERTULIS', 'dsc07438.jpg', '', '', ''),
(5699, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 TES TERTULIS', 'dsc07440.jpg', '', '', ''),
(5700, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 PANITIA SELEKSI PBK GEL 1', 'dsc07450(1).jpg', '', '', ''),
(5701, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 SUASANA TES TERTULIS', '', '', '', ''),
(5702, 'BLKI MAKASSAR', 'irmiani', '02/04/2014', 'SELEKSI PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1', 'TES PENERIMAAN SISWA PELATIHAN BERBASIS KOMPETENSI GEL. 1 RABU, 02 APRIL 2014 TES TERTULIS', 'dsc07451.jpg', '', '', ''),
(5703, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'PT. Mayora Indah Tbk. melaksanakan tes seleksi kerja di BBPLKLN Cevest Bekasi pada hari Kamis, 03 April 2014. Tes seleksi ini diikuti oleh 40 orang alumni pelatihan.', 'spanduk(4).jpg', '', '', ''),
(5704, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'peserta tes seleksi', 'peserta 1.jpg', '', '', ''),
(5705, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'peserta tes', 'peserta 2.jpg', '', '', ''),
(5706, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'peserta tes seleksi', 'peserta 3.jpg', '', '', ''),
(5707, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. MAYORA INDAH DI BBPLKLN CEVEST BEKASI', 'peserta tes seleksi', 'peserta 4.jpg', '', '', ''),
(5708, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. TIRTA ALAM SEGAR', 'PT. TIRTA ALAM SEGAR melaksanakan tes interview di BBPLKLN Cevest Bekasi. Tes ini diikuti oleh 10 orang alumni pelatihan yang terdiri dari alumni pelatihan kejuruan Las dan Fabrikasi.', 'interview 1.jpg', '', '', ''),
(5709, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. TIRTA ALAM SEGAR', 'Pelaksanaan tes interview', 'interview 2.jpg', '', '', ''),
(5710, 'BBPLKLN CEVEST', 'NURHAYATI', '03/04/2014', 'PELAKSANAAN TES SELEKSI KERJA PT. TIRTA ALAM SEGAR', 'peserta tes interview', 'peserta tes interview.jpg', '', '', ''),
(5711, 'BBPLKDN BANDUNG', 'yusnita karolina', '03/04/2014', 'Seleksi PBK 2014', 'Pada hari selasa tanggal 1 April 2014 BBPLKDN Bandung mengadakan seleksi peserta Program Pelatihan Berbasis Kompetensi 2014 untuk kejuruan Otomotif,Listrik,Bangunan,Tek Manufaktur,Tek Las,Bisnis & Manajemen,Tek Informatika dan Aneka Kejuruan', 'edit2pbk2014.jpg', '', '', ''),
(5714, 'BBPLKDN BANDUNG', 'yusnita karolina', '03/04/2014', 'Seleksi Peserta PBK 2014', 'Pada hari selasa tanggal 1 April 2014 BBPLKDN Bandung mengadakan seleksi peserta Program Pelatihan Berbasis Kompetensi 2014 untuk kejuruan Otomotif,Listrik,Bangunan,Tek Manufaktur,Tek Las,Bisnis & Manajemen,Tek Informatika dan Aneka Kejuruan', 'edit1pbk2014.jpg', '', '', ''),
(5715, 'BLKI BANDA ACEH', 'Fahrizal, SE', '04/04/2014', 'Calon Peserta Peserta Pelatihan Berbasis Kompetensi 2014', 'Para Peserta Calon Pelatihan Berbasis Kompetensi 2014 mendengarkan arahan dari panitia', 'c1.jpg', '', '', ''),
(5716, 'BLKI BANDA ACEH', 'Fahrizal, SE', '04/04/2014', 'Calon Peserta Peserta Pelatihan Berbasis Kompetensi 2014', 'Para Calon Peserta Pelatihan Berbasis Kompetensi 2014 sedang mengikuti test tulis', 'c2.jpg', '', '', ''),
(5717, 'BLKI BANDA ACEH', 'Fahrizal, SE', '04/04/2014', 'Calon Peserta Peserta Pelatihan Berbasis Kompetensi 2014', 'Para Calon Peserta Pelatihan sedang mengikuti test wawancara di BLKI Banda Aceh', 'c3.jpg', '', '', ''),
(5718, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '08/04/2014', 'PENGUMUMAN HASIL TEST SELEKSI', 'PENGUMUMAN HASIL TEST SELEKSI PENERIMAAN CALON PESERTA PELATIHAN INSTITUSIONAL ANGKATAN 2 TAHUN 2014 (02 APRIL 2014) KEJURUAN : AUDIO VIDEO', 'audio video [1600x1200].jpg', '', '', ''),
(5719, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '08/04/2014', 'PENGUMUMAN HASIL TEST SELEKSI', 'PENGUMUMAN HASIL TEST SELEKSI PENERIMAAN CALON PESERTA PELATIHAN INSTITUSIONAL ANGKATAN 2 TAHUN 2014 (02 APRIL 2014) KEJURUAN : TATA KECANTIKAN RIAS / RIAS PENGANTIN', 'kecantikan rias [1600x1200].jpg', '', '', ''),
(5720, 'UPTPK BOJONEGORO', 'Mahela Pradiningtiyas', '08/04/2014', 'PENGUMUMAN HASIL TEST SELEKSI', 'PENGUMUMAN HASIL TEST SELEKSI PENERIMAAN CALON PESERTA PELATIHAN INSTITUSIONAL ANGKATAN 2 TAHUN 2014 (02 APRIL 2014) KEJURUAN : MENJAHIT', 'menjahit [1600x1200].jpg', '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `2011infokios`
--
ALTER TABLE `2011infokios`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id_2` (`id`),
  ADD KEY `id` (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `2011infokios`
--
ALTER TABLE `2011infokios`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8175;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
